/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111314-gb40324d417-20230701"
#endif /* AVUTIL_FFVERSION_H */
